name: icenet-edsbook
channels:
  - conda-forge
  - defaults
dependencies:
  - libnetcdf
  - pip
  - python<3.12
  - "tensorflow<2.16=cpu*"
  - pip:
      - icenet @ git+https://github.com/icenet-ai/icenet@3654dc4954eca6d28e16b4876bd6538abd1f0c06
      - ecmwflibs
      - netCDF4==1.6.0
