name: 67a1e320-7c47-4ea9-8df8-e868326bc90b
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cf-units
  - copernicusmarine
  - ipykernel
  - jupyterlab
  - libnetcdf
  - nbdime
  - netcdf4=1.6.0
  - notebook
  - pip
  - python<3.12
  - "tensorflow<2.16=cpu*"
  - pip:
      - ecmwflibs
      - icenet @ git+https://github.com/icenet-ai/icenet@32558347fa8459a4414b5f30af16b04540ba9101
